<?php

use Fisharebest\Webtrees\I18N;

/**
 * @var array<string,string> $options
 * @var string               $title
 * @var string               $label
 * @var string               $labelType
 * @var array                $recordTypes (string => int)
 * @var array                $selectedTypes
 */

?>

<h2 class="wt-page-title"><?= $title ?></h2>

<form method="post" class="wt-page-options wt-page-options-clippings d-print-none">
    <?= csrf_field() ?>

    <div class="row form-group">
        <div class="col-sm-3 col-form-label wt-page-options-label">
            <?= $label ?>
        </div>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/radios', ['name' => 'option', 'options' => $options, 'selected' => key($options)]) ?>
        </div>
    </div>

    <?php if (count($recordTypes) > 1): ?>
        <fieldset class="form-group">
            <div class="row">
                <div class="col-sm-3 col-form-label wt-page-options-label">
                    <?= $labelType ?>
                </div>
                <div class="col-sm-9 wt-page-options-value pt-2">
                    <div id="delete-types">
                        <?php foreach ($recordTypes as $type => $count) : ?>
                            <?php $badge = view('components/badge', ['count' => $count]); ?>
                            <?php $labelBox = $type . ' ' . $badge . '&nbsp;&nbsp;&nbsp;'; ?>
                            <?= view('components/checkbox-inline', ['name' => 'recordTypes', 'id' => 'chkbx-' . $type, 'checked' => $selectedTypes, 'value' => $count, 'label' => $labelBox]) ?>
                        <?php endforeach ?>
                    </div>
                </div>
            </div>
        </fieldset>
    <?php endif ?>

    <div class="row form-group">
        <div class="col-sm-9 wt-page-options-value">
            <button type="submit" class="btn btn-primary">
                <?= view('icons/save') ?>
                <?= /* I18N: A button label. */ I18N::translate('delete') ?>
            </button>
        </div>
    </div>
</form>
